---
kind: pipeline
name: test 1

steps:
- name: unit tests
  image: node:8
  environment:
    THE_SECRET:
      from_secret: my_secret
  commands:
  - env 
  - bash ./test.sh 
---
kind: secret
data:
  my_secret: od0__ahE6YdkRERBInqdOvjDovu7jRlI-2VNN9oMW8AK93yDOd72uMIm0xlv
